[package]
name = "grasp-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grasp = { path = "../grasp" }
egui = "0.23.0"
eframe = "0.23.0"
egui_tiles = "0.3.1"
egui_wgpu_backend = "0.27.0"
egui_winit_platform = "0.20.0"
winit = "0.29.3"
epi = "0.17.0"
env_logger = "0.10.0"
serde = "1.0.190"
rust-ini = "0.20.0"
log = "0.4.20"